### ISSUE TITLE
有空帮忙看下这题，感觉那个递归的逻辑转不出来

### ISSUE THREAD

**Issue by cjphaha** [Juan-King/DailyCoding#1]
https://leetcode-cn.com/problems/er-cha-shu-de-zui-jin-gong-gong-zu-xian-lcof/submissions/
@sarina-creat

**Comment by sarina-creat** [comment]
寻找LCA
- 递归启动：
开启递归左子节点，返回值为 left；
开启递归右子节点，返回值为 right；

- 返回条件：
root == nil， 返回nil
root == p,q值，返回root

- 返回值：
1. 如果找不到p或q就返回null,如果找的到就返回该点   
2. 如果左子树中有p或q,那么就会返回找到的点，或者p和q都有，就返回p、q的公共点，或者p或q都没有就返回nil
3. 如果右子树中有p||q,那么就会返回找到的点，或者p和q都有，就返回p、q的公共点，或者p或q都没有就返回nil
4. left==nil 说明：左子树中没有p或q (往上看最开始的判断语句：找不到就返回nil)

func lowestCommonAncestor(root, p, q *TreeNode) *TreeNode {
    if root == nil {
        return nil
    }
    if root.Val == p.Val || root.Val == q.Val {
        return root
    }
    left := lowestCommonAncestor(root.Left, p, q)
    right := lowestCommonAncestor(root.Right, p, q)
    if left != nil && right != nil {
        return root
    }
    if left == nil {
        return right
    }
    return left
}

[参考题解：](https://leetcode-cn.com/problems/er-cha-shu-de-zui-jin-gong-gong-zu-xian-lcof/solution/mian-shi-ti-68-ii-er-cha-shu-de-zui-jin-gong-gon-7/)

**Comment by cjphaha** [comment]
thx 😬
